uploads = []
generated = []

[[outputs]]
id = "g1QAotLkAzOjZSXSGlGwj"
uri = "file://chouiaar-travel-agency.tar.gz"
type = "unspecified"
title = "جميع ملفات الموقع — chouiaar-travel-agency.tar.gz (96 MB)"

[[outputs]]
id = "y36MB_OCW_hYOSVbNqDxq"
uri = "file://finel_project_chouiaartravel.zip"
type = "unspecified"
title = "finel project chouiaartravel.zip"

[[outputs]]
id = "Hd0-70L6AovQuWEFJ0jI-"
uri = "file://CHOUIAAR_TRAVEL_AGENCY_PROJECT.zip"
type = "unspecified"
title = "CHOUIAAR TRAVEL AGENCY — VPS Package (3.37 MB)"

[[outputs]]
id = "Ys1yuSmhKkYKsIEW-m-VL"
uri = "file://chouiaar_vps.zip"
type = "unspecified"
title = "chouiaar_vps.zip — PORT 8084"

[[outputs]]
id = "QcasJHR6xj2yxgDUtWQld"
uri = "file://chouiaar_full_db.zip"
type = "unspecified"
title = "chouiaar_full_db.zip"

[[outputs]]
id = "eSJKAEUxH8JcdxLc-tEIy"
uri = "file://chouiaar-deploy.tar.gz"
type = "unspecified"
title = "chouiaar-deploy.tar.gz — حزمة النشر الكاملة (5.6MB)"

[[outputs]]
id = "yJ-0woIflv4VKe4nLXcDc"
uri = "file://chouiaar-hostinger.tar.gz"
type = "unspecified"
title = "حزمة النشر — Hostinger VPS (5.2 MB)"

[[outputs]]
id = "5oEdTKOBkxEJ9Km8ITMzW"
uri = "file://chouiaar-project.tar.gz"
type = "unspecified"
title = "ملفات مشروع شويعر كاملة"
